/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Manejo;
import modelo.Vehiculo;

/**
 *
 * @author Mi PC
 */
public class ReporteVehiculos extends javax.swing.JFrame {

    private Automotor automotor;
    Manejo manejo = Manejo.getManejo();
    
    DefaultTableModel modeloMotos = new DefaultTableModel();
    DefaultTableModel modeloCamiones = new DefaultTableModel();
    DefaultTableModel modeloAutos = new DefaultTableModel();
    DefaultTableModel listaGeneral = new DefaultTableModel();
    
    /**
     * Creates new form ReporteVehiculos
     */
    public ReporteVehiculos(){
        initComponents();
        String titulosTablas[] = new String[]{"PLACA", "MARCA", "MODELO", "VALOR COMERCIAL"};
        modeloMotos.setColumnIdentifiers(titulosTablas);
        modeloCamiones.setColumnIdentifiers(titulosTablas);
        modeloAutos.setColumnIdentifiers(titulosTablas);
        
        jtbl_motocicletas.setModel(modeloMotos);
        jtbl_automoviles.setModel(modeloAutos);
        jtbl_camiones.setModel(modeloCamiones);
        
        String titulosGeneral[] = new String[]{"TIPO VEHICULO", "PLACA", "MARCA", "MODELO", "VALOR COMERCIAL"};
        listaGeneral.setColumnIdentifiers(titulosGeneral);
        jtbl_listaGeneral.setModel(listaGeneral);
        
        txt_cantMotos.setText(String.valueOf(manejo.numMotos()));
        txt_cantAutos.setText(String.valueOf(manejo.numAutomoviles()));
        txt_cantCamiones.setText(String.valueOf(manejo.numCamiones()));
        txt_cantTotalVehiculos.setText(String.valueOf(manejo.getPosicion()));
        
        this.automotor = automotor;
        cargarMotos();
        cargarAutos();
        cargarCamiones();
        cargarVehiculos();
    }
    
    public ReporteVehiculos(Automotor automotor) {
        initComponents();
        String titulosTablas[] = new String[]{"PLACA", "MARCA", "MODELO", "VALOR COMERCIAL"};
        modeloMotos.setColumnIdentifiers(titulosTablas);
        modeloCamiones.setColumnIdentifiers(titulosTablas);
        modeloAutos.setColumnIdentifiers(titulosTablas);
        
        jtbl_motocicletas.setModel(modeloMotos);
        jtbl_automoviles.setModel(modeloAutos);
        jtbl_camiones.setModel(modeloCamiones);
        
        String titulosGeneral[] = new String[]{"TIPO VEHICULO", "PLACA", "MARCA", "MODELO", "VALOR COMERCIAL"};
        listaGeneral.setColumnIdentifiers(titulosGeneral);
        jtbl_listaGeneral.setModel(listaGeneral);
        
        txt_cantMotos.setText(String.valueOf(manejo.numMotos()));
        txt_cantAutos.setText(String.valueOf(manejo.numAutomoviles()));
        txt_cantCamiones.setText(String.valueOf(manejo.numCamiones()));
        txt_cantTotalVehiculos.setText(String.valueOf(manejo.getPosicion()));
        
        this.automotor = automotor;
        cargarMotos();
        cargarAutos();
        cargarCamiones();
        cargarVehiculos();
    }
    
    public void setAutomor(Automotor automotor){
        this.automotor = automotor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_motocicletas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_cantMotos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_buscarMoto = new javax.swing.JTextField();
        btn_buscarMoto = new javax.swing.JButton();
        btn_cancelarBusquedaMoto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_automoviles = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cantAutos = new javax.swing.JTextField();
        btn_buscarAuto = new javax.swing.JButton();
        txt_buscarAuto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_cancelarBusquedaAuto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_camiones = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_cantCamiones = new javax.swing.JTextField();
        btn_buscarCamion = new javax.swing.JButton();
        txt_buscarCamion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_cancelarBusquedaCamion = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbl_listaGeneral = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txt_cantTotalVehiculos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_busquedaGeneral = new javax.swing.JButton();
        btn_cancelarBusqueda = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        btn_ordenarLista = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbo_metodoOrdenamiento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reporte de las Motocicletas");

        jtbl_motocicletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_motocicletas);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MOTOCICLETAS");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setText("Cantidad Disponible:");

        txt_cantMotos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Buscar por placa:");

        txt_buscarMoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_buscarMoto.setText("BUSCAR");
        btn_buscarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarMotoActionPerformed(evt);
            }
        });

        btn_cancelarBusquedaMoto.setText("CANCELAR BUSQUEDA");
        btn_cancelarBusquedaMoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancelarBusquedaMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarBusquedaMotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_cancelarBusquedaMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cantMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_buscarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_cantMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscarMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarMoto)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_cancelarBusquedaMoto)
                .addContainerGap())
        );

        jTabbedPane1.addTab("REPORTE MOTOCICLETAS", jPanel2);

        jtbl_automoviles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbl_automoviles);

        jLabel3.setText("Reporte Automoviles");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AUTOMOVILES");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setText("Cantidad Disponible:");

        txt_cantAutos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_buscarAuto.setText("BUSCAR");
        btn_buscarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarAutoActionPerformed(evt);
            }
        });

        txt_buscarAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setText("Buscar por placa:");

        btn_cancelarBusquedaAuto.setText("CANCELAR BUSQUEDA");
        btn_cancelarBusquedaAuto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancelarBusquedaAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarBusquedaAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_cantAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_buscarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btn_cancelarBusquedaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_cantAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarAuto)
                    .addComponent(txt_buscarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_cancelarBusquedaAuto)
                .addContainerGap())
        );

        jTabbedPane1.addTab("REPORTE AUTOMOVILES", jPanel3);

        jtbl_camiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtbl_camiones);

        jLabel5.setText("Reporte Camiones");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CAMIONES");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setText("Cantidad Disponible:");

        txt_cantCamiones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_buscarCamion.setText("BUSCAR");
        btn_buscarCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarCamionActionPerformed(evt);
            }
        });

        txt_buscarCamion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setText("Buscar por placa:");

        btn_cancelarBusquedaCamion.setText("CANCELAR BUSQUEDA");
        btn_cancelarBusquedaCamion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancelarBusquedaCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarBusquedaCamionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_cantCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_buscarCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btn_cancelarBusquedaCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscarCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_cantCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarCamion)
                    .addComponent(txt_buscarCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_cancelarBusquedaCamion)
                .addContainerGap())
        );

        jTabbedPane1.addTab("REPORTE CAMIONES", jPanel4);

        jLabel16.setText("Reporte General");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("REPORTE GENERAL DE VEHICULOS");

        jtbl_listaGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jtbl_listaGeneral);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel18.setText("Cantidad disponible:");

        txt_cantTotalVehiculos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel19.setText("Buscar por placa:");

        txt_buscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_busquedaGeneral.setText("BUSCAR");
        btn_busquedaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaGeneralActionPerformed(evt);
            }
        });

        btn_cancelarBusqueda.setText("CANCELAR BUSQUEDA");
        btn_cancelarBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancelarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cantTotalVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btn_cancelarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btn_busquedaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_cantTotalVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_busquedaGeneral)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btn_cancelarBusqueda)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("REPORTE GENERAL", jPanel5);

        btn_regresar.setText("REGRESAR");
        btn_regresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        btn_ordenarLista.setText("ORDENAR LISTA");
        btn_ordenarLista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ordenarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenarListaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel13.setText("Ordenar la lista de vehiculos");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("REPORTE GENERAL DE VEHICULOS");

        jLabel15.setText("Ordenar por:");

        cbo_metodoOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenar por placa", "Ordenar alfabeticamente", "Ordenar por modelo", "Ordenar por valor comercial" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbo_metodoOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btn_ordenarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ordenarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbo_metodoOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarVehiculos(){
        listaGeneral.setRowCount(0);
        for(int i=0; i < manejo.getPosicion(); i++){
            Vehiculo vehiculos;
            
            vehiculos = manejo.getLista(i);
            String tipoVehiculo = vehiculos.getTipoVehiculo();
            String placa = vehiculos.getPlaca();
            String marca = vehiculos.getMarca();
            int modelo = vehiculos.getModelo();
            float valor = vehiculos.getValorComercial();

            Object lista[] = new Object[]{tipoVehiculo, placa, marca, modelo, valor};
            listaGeneral.addRow(lista);
        }
    }
    
    private void cargarMotos(){
        modeloMotos.setRowCount(0);
        for(int i=0; i < manejo.getPosicion(); i++){
            Vehiculo vehiculos;
            if(manejo.getLista(i).getTipoVehiculo().equals("Motocicleta")){
                vehiculos = manejo.getLista(i);
                String placa = vehiculos.getPlaca();
                String marca = vehiculos.getMarca();
                int modelo = vehiculos.getModelo();
                float valor = vehiculos.getValorComercial();
                
                Object lista[] = new Object[]{placa, marca, modelo, valor};
                modeloMotos.addRow(lista);
            }
        }
    }
    
    private void cargarAutos(){
        modeloAutos.setRowCount(0);
        for(int i=0; i < manejo.getPosicion(); i++){
            Vehiculo vehiculos;
            if(manejo.getLista(i).getTipoVehiculo().equals("Automovil")){
                vehiculos = manejo.getLista(i);
                String placa = vehiculos.getPlaca();
                String marca = vehiculos.getMarca();
                int modelo = vehiculos.getModelo();
                float valor = vehiculos.getValorComercial();
                
                Object lista[] = new Object[]{placa, marca, modelo, valor};
                modeloAutos.addRow(lista);
            }
        }
    }
    
    private void cargarCamiones(){
        modeloCamiones.setRowCount(0);
        for(int i=0; i < manejo.getPosicion(); i++){
            Vehiculo vehiculos;
            if(manejo.getLista(i).getTipoVehiculo().equals("Camion")){
                vehiculos = manejo.getLista(i);
                String placa = vehiculos.getPlaca();
                String marca = vehiculos.getMarca();
                int modelo = vehiculos.getModelo();
                float valor = vehiculos.getValorComercial();
                
                Object lista[] = new Object[]{placa, marca, modelo, valor};
                modeloCamiones.addRow(lista);
            }
        }
    }
    
    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        automotor.setVisible(true);
        automotor.setResizable(false);
        automotor.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_buscarMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarMotoActionPerformed
        try{
            int posicion = manejo.busquedaBinaria(txt_buscarMoto.getText());
            Vehiculo vehiculo;
            
            if(manejo.getLista(posicion).getTipoVehiculo().equals("Motocicleta") && posicion != -1){
                vehiculo = manejo.getLista(posicion);

                modeloMotos.setRowCount(0);
                String placa = vehiculo.getPlaca();
                String marca = vehiculo.getMarca();
                int modelo = vehiculo.getModelo();
                float valor = vehiculo.getValorComercial();

                Object lista[] = new Object[]{placa, marca, modelo, valor};
                modeloMotos.addRow(lista);
            }else{
                JOptionPane.showMessageDialog(null, "La placa ingresada no pertenece a una moto.", null, JOptionPane.ERROR_MESSAGE);
                txt_buscarMoto.grabFocus();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_buscarMotoActionPerformed

    private void btn_buscarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarAutoActionPerformed
        try{
            int posicion = manejo.busquedaBinaria(txt_buscarAuto.getText());
            Vehiculo vehiculo;
            
            if(manejo.getLista(posicion).getTipoVehiculo().equals("Automovil") && posicion != -1){
                vehiculo = manejo.getLista(posicion);

                modeloAutos.setRowCount(0);
                String placa = vehiculo.getPlaca();
                String marca = vehiculo.getMarca();
                int modelo = vehiculo.getModelo();
                float valor = vehiculo.getValorComercial();

                Object lista[] = new Object[]{placa, marca, modelo, valor};
                modeloAutos.addRow(lista);
            }else{
                JOptionPane.showMessageDialog(null, "La placa ingresada no pertenece a un auto.", null, JOptionPane.ERROR_MESSAGE);
                txt_buscarMoto.grabFocus();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_buscarAutoActionPerformed

    private void btn_buscarCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarCamionActionPerformed
        try{
            int posicion = manejo.busquedaBinaria(txt_buscarCamion.getText());
            Vehiculo vehiculo;
            
            if(manejo.getLista(posicion).getTipoVehiculo().equals("Camion") && posicion != -1){
                vehiculo = manejo.getLista(posicion);

                modeloCamiones.setRowCount(0);
                String placa = vehiculo.getPlaca();
                String marca = vehiculo.getMarca();
                int modelo = vehiculo.getModelo();
                float valor = vehiculo.getValorComercial();

                Object lista[] = new Object[]{placa, marca, modelo, valor};
                modeloCamiones.addRow(lista);
            }else{
                JOptionPane.showMessageDialog(null, "La placa ingresada no pertenece a un camion.", null, JOptionPane.ERROR_MESSAGE);
                txt_buscarMoto.grabFocus();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_buscarCamionActionPerformed

    private void btn_cancelarBusquedaCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarBusquedaCamionActionPerformed
        try{
            cargarCamiones();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_cancelarBusquedaCamionActionPerformed

    private void btn_cancelarBusquedaAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarBusquedaAutoActionPerformed
        try{
            cargarAutos();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_cancelarBusquedaAutoActionPerformed

    private void btn_cancelarBusquedaMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarBusquedaMotoActionPerformed
        try{
            cargarMotos();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_cancelarBusquedaMotoActionPerformed

    private void btn_ordenarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenarListaActionPerformed
        try{
            int opcion = cbo_metodoOrdenamiento.getSelectedIndex();
            
            switch(opcion){
                case 0:
                    manejo.ordenamientoShell();
                    cargarAutos();
                    cargarCamiones();
                    cargarMotos();
                    cargarVehiculos();
                    break;
                case 1:
                    manejo.ordenamientoIntercambiado();
                    cargarAutos();
                    cargarCamiones();
                    cargarMotos();
                    cargarVehiculos();
                    break;
                case 2:
                    manejo.ordenamientoBurbuja();
                    cargarAutos();
                    cargarCamiones();
                    cargarMotos();
                    cargarVehiculos();
                    break;
                case 3:
                    manejo.ordenarSeleccion();
                    cargarAutos();
                    cargarCamiones();
                    cargarMotos();
                    cargarVehiculos();
                    break;
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al ordenar la lista.", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ordenarListaActionPerformed

    private void btn_busquedaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaGeneralActionPerformed
        try{
            int posicion = manejo.busquedaBinaria(txt_buscar.getText());
            Vehiculo vehiculo;
            
            if(posicion < manejo.getPosicion() && posicion != -1){
                vehiculo = manejo.getLista(posicion);

                listaGeneral.setRowCount(0);
                String tipoVehiculo = vehiculo.getTipoVehiculo();
                String placa = vehiculo.getPlaca();
                String marca = vehiculo.getMarca();
                int modelo = vehiculo.getModelo();
                float valor = vehiculo.getValorComercial();

                Object lista[] = new Object[]{tipoVehiculo, placa, marca, modelo, valor};
                listaGeneral.addRow(lista);
            }else{
                JOptionPane.showMessageDialog(null, "No se encontro la placa buscada.", null, JOptionPane.ERROR_MESSAGE);
                txt_buscarMoto.grabFocus();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_busquedaGeneralActionPerformed

    private void btn_cancelarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarBusquedaActionPerformed
        try{
            cargarVehiculos();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_cancelarBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarAuto;
    private javax.swing.JButton btn_buscarCamion;
    private javax.swing.JButton btn_buscarMoto;
    private javax.swing.JButton btn_busquedaGeneral;
    private javax.swing.JButton btn_cancelarBusqueda;
    private javax.swing.JButton btn_cancelarBusquedaAuto;
    private javax.swing.JButton btn_cancelarBusquedaCamion;
    private javax.swing.JButton btn_cancelarBusquedaMoto;
    private javax.swing.JButton btn_ordenarLista;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cbo_metodoOrdenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtbl_automoviles;
    private javax.swing.JTable jtbl_camiones;
    private javax.swing.JTable jtbl_listaGeneral;
    private javax.swing.JTable jtbl_motocicletas;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_buscarAuto;
    private javax.swing.JTextField txt_buscarCamion;
    private javax.swing.JTextField txt_buscarMoto;
    private javax.swing.JTextField txt_cantAutos;
    private javax.swing.JTextField txt_cantCamiones;
    private javax.swing.JTextField txt_cantMotos;
    private javax.swing.JTextField txt_cantTotalVehiculos;
    // End of variables declaration//GEN-END:variables
}
